# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vedantdhavan
# "service" is the name of this project. This will also be added to your AWS resource names.
service: contentos-backend

provider:
  name: aws
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  region: us-east-1
  profile: vedant_dhavan
  timeout: 25
  memorySize: 2048

  httpApi:
    cors:
      allowedOrigins:
        - "http://localhost:5173"
      allowedMethods:
        - POST
        - GET
        - OPTIONS
      allowedHeaders:
        - Content-Type
      allowCredentials: false

  iam:
    role:
      statements:
        # Bedrock Access
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
          Resource: "*"

        # DynamoDB Write
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource: "*"

        # NEW — S3 Upload Permission
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
            - arn:aws:s3:::contentos-assets/*

functions:
  agent:
    handler: handler.agent
    events:
      - httpApi:
          path: /agent
          method: post

  campaigns:
    handler: handler.getCampaigns
    events:
      - httpApi:
          path: /campaigns
          method: get
